baseURL = 'https://peaplesmart.github.io/'
languageCode = 'id'
defaultContentLanguage = 'id'
title = 'Octocat Kode'
ignoreLogs = ['warning-goldmark-raw-html']
enableRobotsTXT = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "topik"
  weight = 100

[[related.indices]]
  name = "series"
  weight = 80

[[related.indices]]
  name = "software"
  weight = 80

[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'

[taxonomies]
  kategori = "kategori"
  topik = "topik"

[outputs]
  home = ["HTML", "SearchIndex"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.SearchIndex]
    name = "SearchIndex"
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

[params]
  author = "default"
  description = "Deskripsi situs saya"
